import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    absolute: 'Iniciar Novo Template',
  },
  description: 'Generated by create next app',
}

const GetStarted = () => {
  return <div>GetStarted</div>
}

export default GetStarted
