import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Planos',
  description: 'Generated by create next app',
}

const PricingPage = () => {
  return <div>PricingPage</div>
}

export default PricingPage
